name: Deploy to Amazon ECS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      ####################################################
      # BACKEND
      ####################################################

      - name: Build Backend
        run: docker build -t backend:${{ github.sha }} ./backend

      - name: Push Backend
        run: |
          docker tag backend:${{ github.sha }} $ECR_REGISTRY/backend:${{ github.sha }}
          docker push $ECR_REGISTRY/backend:${{ github.sha }}

      ####################################################
      # FRONTEND
      ####################################################

      - name: Build Frontend
        run: docker build -t frontend:${{ github.sha }} ./frontend

      - name: Push Frontend
        run: |
          docker tag frontend:${{ github.sha }} $ECR_REGISTRY/frontend:${{ github.sha }}
          docker push $ECR_REGISTRY/frontend:${{ github.sha }}

      ####################################################
      # ECS DEPLOY
      ####################################################

      - name: Deploy Backend Service
        run: |
          aws ecs update-service \
            --cluster fullstack-cluster \
            --service backend-service \
            --force-new-deployment

      - name: Deploy Frontend Service
        run: |
          aws ecs update-service \
            --cluster fullstack-cluster \
            --service frontend-service \
            --force-new-deployment
